---
name: Verify Images
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crs-version:
          - "3.3.2"
        image:
          - apache
          - nginx
        variant:
          - ""
          - "-alpine"
        platform:
          - linux/amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master

      - name: Build ${{ matrix.crs-version }}-${{ matrix.image }}${{ matrix.variant }}
        uses: docker/bake-action@v1.5.0
        with:
          files: docker-bake.hcl
          targets: ${{ matrix.image }}${{ matrix.variant }}
          set: |
            "${{ matrix.image }}${{ matrix.variant }}.tags=${{ matrix.crs-version }}-${{ matrix.image }}${{ matrix.variant }}-test"
            "${{ matrix.image }}${{ matrix.variant }}.platform=${{ matrix.platform }}"
          load: true
          push: false

      - name: Run ${{ matrix.image }}${{ matrix.variant }}
        run: |
          docker run -d --name ${{ matrix.crs-version }}-${{ matrix.image }}${{ matrix.variant }}-test ${{ matrix.crs-version }}-${{ matrix.image }}${{ matrix.variant }}-test
          docker logs ${{ matrix.crs-version }}-${{ matrix.image }}${{ matrix.variant }}-test

      - name: Verify ${{ matrix.crs-version }}-${{ matrix.image }}${{ matrix.variant }}
        run: |
          [ $(docker inspect ${{ matrix.crs-version }}-${{ matrix.image }}${{ matrix.variant }}-test --format='{{.State.Running}}') = 'true' ]
